setup:
	mkdir -p ../shared/ && ganache-cli -m "frown edit talent kid achieve student runway path door work noodle better" --account_keys_path "../shared/GanacheKeys.json"

migrate:
	truffle migrate

run-test:
	truffle test
